[versions]
androidGradlePlugin = "8.13.2"
kotlin = "2.2.21"
hilt = "2.57.2"
navigation = "2.9.6"
ksp = "2.2.21-2.0.4"
androidxCore = "1.17.0"
androidxAppCompat = "1.7.1"
material = "1.13.0"
constraintLayout = "2.2.1"
androidxLifecycle = "2.10.0"
androidxFragment = "1.8.9"
junit = "4.13.2"
jupiter = "6.0.1"
androidxTestExt = "1.3.0"
espresso = "3.7.0"
okhttp = "5.3.2"
retrofit = "3.0.0"
kserialization = "1.9.0"
coroutines = "1.10.2"
secretsGradlePlugin = "2.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore"}
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat"}
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
material = { group = "com.google.android.material", name = "material", version.ref = "material"}
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout"}
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name="hilt-android-compiler", version.ref = "hilt" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation"}
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation"}
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version = "1.0.0" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle"}
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle"}
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment"}
junit = { group = "junit", name = "junit", version.ref = "junit"}
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "jupiter"}
junitParams = {group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "jupiter"}
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt"}
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso"}
androidx-navigation-safe-args-gradle-plugin = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation"}
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kserialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kserialization" }

net-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
net-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp"}

net-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
net-retrofit-kotlin = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0"}

[bundles]
net= ["net-okhttp", "net-okhttp-logging", "net-retrofit", "net-retrofit-kotlin"]
coroutines = ["kotlin-coroutines-core", "kotlin-coroutines-android"]
serialization = ["kotlin-serialization-core", "kotlin-serialization-json"]


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation"}
secrets-gradle-plugin = {id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin"}